### ISSUE TITLE
如何在后台运行？

### ISSUE THREAD

**Issue by yiyione** [LXY1226/MiraiOK#1]
我直接运行 `./miraiOK_linux_amd64` 是可以正常启动的
但是改成 `./miraiOK_linux_amd64 > log.out &` 或者 `nohup ./miraiOK_linux_amd64 &` 都会启动失败
第一个是停在了：
```
[15:20:35.7743] I 删除.lastupdate来在下次强制检查更新
[15:20:35.7743] I 启动Mirai...
```
第二个则是会报错：
```
[15:29:42 [INFO] [Mirai 0.5.2 Pkmon] "login qq号 qq密码 " 来登录一个BOT
[15:29:42 [INFO] [CQHTTPMirai] 反向Websocket模块已禁用
[15:29:42 [INFO] [Mirai 0.5.2 Pkmon] kotlinx.coroutines.JobCancellationException: LazyStandaloneCoroutine was cancelled; job=LazyStandaloneCoroutine{Cancelling}@60e9b7a2

[15:29:42.4692] E 运行失败，尝试更新mirai三件套 read /dev/stdin: bad file descriptor
[15:29:42.4694] I 开始检查Mirai更新... 也可以通过创建.noupdate文件来禁用更新
[15:29:42.9767] I 初始化远程存储成功
[15:29:43.5406] E 无法启动 exec: already started
按回车退出...
请尝试清空文件，重新下载此程序
```

请问有什么解决办法么？

**Comment by LXY1226** [comment]
大概是console的feature...
没有stdin就暴死...
暂时与miraiOK无关，但是会尝试修一下，前几天也遇到同样的问题

**Comment by LXY1226** [comment]
后台的话暂时只能screen -l

**Comment by yf4n** [comment]
（我没有用过，路过看到这个问题）
不知道docker能不能解决你的后台运行的问题。

**Comment by Menci** [comment]
用 systemd 也会有这个问题，而且更奇怪的是，我手动启动一次然后用 systemd 运行，就没问题了

**Comment by predit-wzj** [comment]
可以试一下setsid

**Comment by traceless0929** [comment]
我这是可行的 nohup ./miraiOK_linux_amd64 &

**Comment by predit-wzj** [comment]
> 我这是可行的 nohup ./miraiOK_linux_amd64 &

如果你有GUI当然可行，或者VNC的也可以，直接ssh进行的nohup照逻辑来说是不可行的

**Comment by traceless0929** [comment]
> > 我这是可行的 nohup ./miraiOK_linux_amd64 &
> 
> 如果你有GUI当然可行，或者VNC的也可以，直接ssh进行的nohup照逻辑来说是不可行的

用的finalShell

**Comment by duanluan** [comment]
> 我直接运行 `./miraiOK_linux_amd64` 是可以正常启动的 但是改成 `./miraiOK_linux_amd64 > log.out &` 或者 `nohup ./miraiOK_linux_amd64 &` 都会启动失败 第一个是停在了：
> 
> ```
> [15:20:35.7743] I 删除.lastupdate来在下次强制检查更新
> [15:20:35.7743] I 启动Mirai...
> ```
> 
> 第二个则是会报错：
> 
> ```
> [15:29:42 [INFO] [Mirai 0.5.2 Pkmon] "login qq号 qq密码 " 来登录一个BOT
> [15:29:42 [INFO] [CQHTTPMirai] 反向Websocket模块已禁用
> [15:29:42 [INFO] [Mirai 0.5.2 Pkmon] kotlinx.coroutines.JobCancellationException: LazyStandaloneCoroutine was cancelled; job=LazyStandaloneCoroutine{Cancelling}@60e9b7a2
> 
> [15:29:42.4692] E 运行失败，尝试更新mirai三件套 read /dev/stdin: bad file descriptor
> [15:29:42.4694] I 开始检查Mirai更新... 也可以通过创建.noupdate文件来禁用更新
> [15:29:42.9767] I 初始化远程存储成功
> [15:29:43.5406] E 无法启动 exec: already started
> 按回车退出...
> 请尝试清空文件，重新下载此程序
> ```
> 
> 请问有什么解决办法么？

不用管这个错误。
nohup ./mcl > /dev/null &
