### ISSUE TITLE
[功能请求]能不能加一个使用指定版本内核的功能?

### ISSUE THREAD

**Issue by asjdf** [LXY1226/MiraiOK#15]
mirai-api-http那个插件没有支持到最新的内核.
另外问一下能不能手动把内核换掉并关闭更新.

**Comment by LXY1226** [comment]
合理请求
但是目前没法搞...
而且目前也没有乱更新的情况...
需要食用测试版的话，非常不建议用miraiok，他只是用来入门而不是开发
欢迎pr个能处理versions.json的版本
