### ISSUE TITLE
部署到海外vps更新失败，按照提示创建.noupdate 文件无法禁用更新

### ISSUE THREAD

**Issue by bai-lu** [LXY1226/MiraiOK#17]

**Comment by LXY1226** [comment]
我就想知道你怎么想的
更新失败就不让他更新
哦
然后呢
啥也没有让它裸跑？

miraiok:我更新失败了
你：哦那你别更新
miraiok:那你看着办
你：？

**Comment by bai-lu** [comment]
莫名其妙挨怼，您标题看完了吗？ 根据miraiok 提示创建了.noupdate  , miraiok 仍旧会触发更新

**Comment by LXY1226** [comment]
那么您看完我说的什么意思了吗
miraiok是一个下载器
不是机器人

**Comment by LXY1226** [comment]
之前有issue说过不会提供海外服务器支持
这个软件也不打算提供给海外用户使用
请你们用你们喜欢的方式下载并且遵守mirai主页面的启动方式启动
可以了吗

**Comment by bai-lu** [comment]
我没别的问题了

**Comment by LXY1226** [comment]
那你不close等我吗

**Comment by bai-lu** [comment]
手速比不过你， nb
