### ISSUE TITLE
miraiOK好像没办法接受消息了

### ISSUE THREAD

**Issue by Syize** [LXY1226/MiraiOK#18]
版本是Linux arm，运行在树莓派4b上，指令say仍然可以使用，但是在向机器人发送消息是不再出现以前的消息框而是unknown type
![2020-07-12 10-26-43屏幕截图](https://user-images.githubusercontent.com/44666294/87237569-8eb33080-c42a-11ea-8e16-076eddab8d2a.png)

**Comment by Syize** [comment]
我在昨天晚上测试的时候是正常的，今天早晨继续测试的时候发现已经不能再接收消息了

**Comment by Syize** [comment]
重启过一次，没有解决问题

**Comment by LXY1226** [comment]
这不是聊天软件
