### ISSUE TITLE
***关于出现进度条的统一回复

### ISSUE THREAD

**Issue by LXY1226** [LXY1226/MiraiOK#19]
就是你网烂的一批 miraiok拉jar拉一半网残了
然后留下个半残jar被wrapper加载，然后报错，然后会去成尸体的崔云那下载东西

解决方案
快来pr个下载后校验
方法：在下面留言你的想法，然后我会把mirai盘的开启方式给你。

这个项目已经招来了比我意料之中更多的憨批....
所以，下个新wrapper来临之前应该不会更新而去搓别的东西了。

**Comment by Cyenoch** [comment]
笑死我了233333
