### ISSUE TITLE
希望可以新增 Github Release 分发方式，以及给 t.imlxy.net 服务器新增 https 支持

### ISSUE THREAD

**Issue by linepro6** [LXY1226/MiraiOK#2]
新增 Github Release 分发方式可以方便境外服务器的下载和更新。
给 t.imlxy.net 服务器新增 https 支持有利于安全性。

**Comment by LXY1226** [comment]
emm
0. 软件并不打算提供给国外/有国外服务器的国人使用，因为最近有一些来自国外服务器的报告指出在国外网络使用mirai会有一些奇怪的问题...
1.release在actions里有，而t.imlxy net的内容与actions里的release一样
图方便而没有使用tag/release罢了，因为现在跟mirai本体一样处于快速迭代期，所以没有发release而是把每版本都作为类似release的东西了
2. t.imlxy.net暂时不太需要考虑https....它和miraiOK的download.go里一样使用Onedrive作为文件来源，t.imlxy.net的那个端口也只是作为跳板跳转到onedrive下载，301之后的链接是https的，这点问题不大。

如果还有什么建议的话请留下comment，如果没有的话可以close了呢~

**Comment by benbenlike** [comment]
讲道理使用境外服务器是件很平常的事情，除了延迟可能会高一点，各种方面的优势远大于国内服务器。

**Comment by LXY1226** [comment]
emm...
目前miraiOK具有在国外服务器上运行的能力，而且应该除了下载服务器在国内而可能导致的下载出错之外没有任何问题。
也可以在actions里下载最新的Artifacts，对国外服务器会友好很多。
其他方面 我认为保持原状足够了，目前主要精力投在miraiGo上而不在这里...
这个项目的生态也已经成了闭环，自动编译，自动发布自动更新都已经完成了。

**Comment by linepro6** [comment]
虽然概率比较低，不过如果被别有用心的人修改了 t.imlxy.net 发送的 302 响应的话也算是一件挺危险的事情吧。
当然这个优先级确实不是很高就是了~
还有一个问题，在 OpenWRT x86 环境下执行 MiraiOK 没有任何输出，终端得到的返回值是 127，是否是正常行为？是否需要新开 issue？

**Comment by LXY1226** [comment]
被修改的概率远比lightProvider(跳板程序)出错的概率低...
127错误请参照这里 https://stackoverflow.com/questions/1763156/127-return-code-from

**Comment by linepro6** [comment]
miraiOK 的二进制文件本身系统应该是识别到了的，这里问题应该是依赖的库没有找到。不过不知道怎么排查。想在 Ubuntu 下使用 ldd 命令查看依赖的库，提示是 not a dynamic executable。
