### ISSUE TITLE
运行一段时间后无响应(控制台无新信息且机器人也没有反应)

### ISSUE THREAD

**Issue by Cicini** [LXY1226/MiraiOK#21]
已确认不是网络原因造成文件未完全下载
运行miraiOK后一段时间(确认已经正常运行一段时间)控制台没有任何信息更新
同时机器人在QQ中没有任何反应
随后进入后台
回车一下弹出错误信息
`[19:00:08.4250] E 运行失败，尝试更新mirai三件套 exit status 1`
`[19:00:08.4252] I 开始检查Mirai更新... 也可以通过创建.noupdate文件来禁用更新`
`[19:00:09.8407] E 无法启动 exec: already started`
`按回车退出...`
`请尝试清空文件，重新下载此程序`
![mirai_error_20200727](https://cicini.moe/static/2020/07/mirai_error_20200727.png)
图片信息中空行为回车键输入
系统：Debian 10 amd64
含有的插件：cqhttp-mirai (yyuueexxiinngg/cqhttp-mirai)

**Comment by LXY1226** [comment]
可以确认的一点是与这问题miraiOK无关
但是有可能是因为miraiOK得版本过低
但是就我那得情况....Bot已经跑了一个多月完全没有出现任何问题
我会跟mirai得开发者讨论一下

**Comment by Cicini** [comment]
> 可以确认的一点是与这问题miraiOK无关
> 但是有可能是因为miraiOK得版本过低
> 但是就我那得情况....Bot已经跑了一个多月完全没有出现任何问题
> 我会跟mirai得开发者讨论一下

emmm 版本低大概可以排除 通过readme上面写的下载地址下载的
谢谢了

**Comment by 952994221** [comment]
问题同上，log如下
![批注 2020-07-30 100658](https://user-images.githubusercontent.com/52597664/88872306-73c72580-d24c-11ea-8639-b63d5b25c4b8.jpg)
系统：Ubuntu 18.04.4 LTS
插件：cqhttp-mirai (yyuueexxiinngg/cqhttp-mirai)

**Comment by Cicini** [comment]
> 问题同上，log如下
> ![批注 2020-07-30 100658](https://user-images.githubusercontent.com/52597664/88872306-73c72580-d24c-11ea-8639-b63d5b25c4b8.jpg)
> 系统：Ubuntu 18.04.4 LTS
> 插件：cqhttp-mirai (yyuueexxiinngg/cqhttp-mirai)

你可以回复一下作者，不然可能看不见吧.

**Comment by LXY1226** [comment]
> > 问题同上，log如下
> > ![批注 2020-07-30 100658](https://user-images.githubusercontent.com/52597664/88872306-73c72580-d24c-11ea-8639-b63d5b25c4b8.jpg)
> > 系统：Ubuntu 18.04.4 LTS
> > 插件：cqhttp-mirai (yyuueexxiinngg/cqhttp-mirai)
> 
> 你可以回复一下作者，不然可能看不见吧.

完全看得见，原因不知道，没这问题，跑得很舒坦，建议自己多调调
(Debian 10 at AliCloud

注：不建议在国外机器跑，下载源在国内，损坏几率大得多，也并不太打算提供换源行为，这东西应该只作为入门砖，能稳定得跑起来就ok
图示部分在源码里有，[极易读](https://github.com/LXY1226/MiraiOK/blob/master/main.go#L81)

**Comment by Cicini** [comment]
> > > 问题同上，log如下
> > > ![批注 2020-07-30 100658](https://user-images.githubusercontent.com/52597664/88872306-73c72580-d24c-11ea-8639-b63d5b25c4b8.jpg)
> > > 系统：Ubuntu 18.04.4 LTS
> > > 插件：cqhttp-mirai (yyuueexxiinngg/cqhttp-mirai)
> > 
> > 
> > 你可以回复一下作者，不然可能看不见吧.
> 
> 完全看得见，原因不知道，没这问题，跑得很舒坦，建议自己多调调
> (Debian 10 at AliCloud
> 
> 注：不建议在国外机器跑，下载源在国内，损坏几率大得多，也并不太打算提供换源行为，这东西应该只作为入门砖，能稳定得跑起来就ok
> 图示部分在源码里有，[极易读](https://github.com/LXY1226/MiraiOK/blob/master/main.go#L81)

可能确实是因为国外机子的原因？(实际上下载方面并没有出问题)
主要还是方面web端的443端口(
问题不大现在分尸运行
mirai在国内，http那端在国外

**Comment by Sincky** [comment]
我也遇到了，也是外国的服务器，用的screen来运行的mirai，一退出ssh就会断线，排查了一晚上，把core降回到1.0.0，console5.2.0就没问题了。希望对你有所帮助。

**Comment by Cicini** [comment]
> 我也遇到了，也是外国的服务器，用的screen来运行的mirai，一退出ssh就会断线，排查了一晚上，把core降回到1.0.0，console5.2.0就没问题了。希望对你有所帮助。

晚点试试，谢谢了，我倒不是断开ssh断线，不管断不断ssh都会卡住无响应(可惜了miraiOK被整没了)
