### ISSUE TITLE
关于miraiOK版本更新的问题

### ISSUE THREAD

**Issue by Genanik** [LXY1226/MiraiOK#22]
最近miraiOK把mirai-core更新到了1.1.3（以前用的是1.0.3），结果bot出了很多很多问题。。研究了下发现在更新之前创建Bot对象使用的是mirai-core，但是现在创建Bot对象使用的是mirai-core-qqandroid，导致一些依赖mirai-core的插件无法使用，请问这个是miraiOK的问题嘛（
啊对，写mirai-console插件的时候用runMiraiConsole创建Bot对象使用的是mirai-core

miraiOK：20200629.160938
mirai-console-wrapper：1.3.0
mirai-core：mirai-core-qqandroid-1.1.3.jar
mirai-console：0.5.2

**Comment by LXY1226** [comment]
显然不是
但是更新是我的锅
群里一群要更新的，本不想来着
如果能做到的话让miraiok不再能访问网络也许能解决更新的问题，之后手动回滚到1.0.3吧

或者找新core进行迭代更新
以后这鬼东西不更了

**Comment by Genanik** [comment]
啊这x
好吧（谢谢谢谢
