### ISSUE TITLE
备份，祝好

### ISSUE THREAD

**Issue by NyaMisty** [LXY1226/MiraiOK#23]
最新版的备份）

抱歉 暂时删除

**Comment by Camusama** [comment]
实在下不动，能分享网盘不 只需要  miraiOK_linux_arm64和amd64

**Comment by rainsmen** [comment]
老兄 能分享个么 多谢

**Comment by Syize** [comment]
去我仓库找，我只有两个

**Comment by Syize** [comment]
另外，求一个arm版的，不是arm64，是arm

**Comment by Syize** [comment]
> 实在下不动，能分享网盘不 只需要 miraiOK_linux_arm64和amd64

我有，去我仓库找
