### ISSUE TITLE
后台运行的问题：screen运行几个小时后卡死

### ISSUE THREAD

**Issue by metatroncube** [LXY1226/MiraiOK#30]
要想后台运行，似乎只有screen才行（nohup setsid & 什么的都不行）
但是，screen运行一段时间（大约两个小时），机器人就自动暂停了（screen和miraiOk的进程都还一直存在）

恢复screen之后发现，miraiOK输出的日志信息在某一时刻开始暂停，卡住不动了，不再接收消息了。想知道有没有修复或者其它后台运行方法的？谢谢！

**Comment by metatroncube** [comment]
补充：Linux Debian 9 

据群友说，在windows上这个问题更常见

**Comment by lstkpeter** [comment]
ubuntu 18.04 arm64发生同样问题

**Comment by lstkpeter** [comment]
screen挂起之后，ssh连接断开一会就会掉线，恢复screen后，回车输出

[16:23:52.1536] E 运行失败，尝试更新mirai三件套 exit status 1
[16:23:52.1545] I 开始检查Mirai更新... 也可以通过创建.noupdate文件来禁用更新
[16:23:53.5989] I 初始化远程存储成功
[16:23:56.8086] E 无法启动 exec: already started
按回车退出...
请尝试清空文件，重新下载此程序

**Comment by hkai1221** [comment]
群内还可以加人吗，想进群交流。

**Comment by metatroncube** [comment]
@hkai1221 
780718903 qq

**Comment by XYZliang** [comment]
Windows下经常发生，也是突然控制台输出的日志信息突然没了。插件却运行正常，但是不能发信息（cqhttp）
