### ISSUE TITLE
Mirai版本更新问题

### ISSUE THREAD

**Issue by 1523789353** [LXY1226/MiraiOK#32]
mirai-core-qqandroid-1.1.3 (也就是Mirai1.1.3)遇到了一个问题
[Mirai-Issue518](https://github.com/mamoe/mirai/issues/518)

然后Him188告诉我要更新MiraiOK
更新MiraiOK然并卵,Mirai版本还是1.1.3
XD

**Comment by LXY1226** [comment]
更新能整出更多问题
建议手动更新配.NOUPDATE
