### ISSUE TITLE
[BUG/FEATURE]通过NOUPDATE来禁用自更新不奏效

### ISSUE THREAD

**Issue by hizo58** [LXY1226/MiraiOK#34]
尝试1.
在config.txt同级目录加.noupdate文件
尝试2.
在config.txt同级目录加.NOUPDATE文件

https://github.com/LXY1226/MiraiOK/blob/93cc37d9147ce6f558d57990d2c321575bc3828b/main.go#L54

尝试3.
在config.txt文件内解除注释NOUPDATE

https://github.com/LXY1226/MiraiOK/blob/93cc37d9147ce6f558d57990d2c321575bc3828b/config.go#L62

皆没有效果，content内有1.2.2（或其他）core时候仍然会尝试下载并使用1.1.3
但这是偶然情况，不是每次重启都会尝试下载并使用1.1.3

**Comment by hizo58** [comment]
LXY:
最好的解决方式就是

下一个1.2.2

重命名成1.1.3

**Comment by zx900930** [comment]
Windows下亲测有效，你是不是什么地方写错了
![image](https://user-images.githubusercontent.com/734749/91274904-b44c8d00-e77f-11ea-9f76-94ff14d7bc72.png)
![image](https://user-images.githubusercontent.com/734749/91275431-7439da00-e780-11ea-98cd-36309dbff2d7.png)

**Comment by 1523789353** [comment]
同.自动更新概率还蛮高的...

**Comment by TheLZY** [comment]
的确，我这里是一次有效一次无效。所以每次打开，都要等他下完了1.1.3后删掉再打开一次
![image](https://user-images.githubusercontent.com/32624562/91640113-c400f580-ea4d-11ea-923f-f542d309fedb.png)

删了再打开：
![image](https://user-images.githubusercontent.com/32624562/91640127-e430b480-ea4d-11ea-8b99-ff5968f7b6a2.png)
