### ISSUE TITLE
关于自动更新

### ISSUE THREAD

**Issue by 1523789353** [LXY1226/MiraiOK#35]
能不能直接从api.github.com拉取文件列表,在用代理下载
https://api.github.com/repos/project-mirai/mirai-repo/contents/shadow/mirai-core-qqandroid
https://api.github.com/repos/project-mirai/mirai-repo/contents/shadow/mirai-console

#代理:
下载文件时https://github.com替换成http://github-proxy.yobot.win即可代理
比如说http://github-proxy.yobot.win/project-mirai/mirai-repo/blob/master/shadow/mirai-core-qqandroid/mirai-core-qqandroid-1.2.2.jar

**Comment by LXY1226** [comment]
1. 拉多个列表显然不如只拉一次好
2. 解决不了国内访问，尤其现在这用量...任何代理都有拉瘫的风险，届时全员爆炸
2.1 可以自己加storinfo.go添加你认为ok的源来试速度，快再来找我
3. 不如gitee
