### ISSUE TITLE
native 1.9.1非管理员模式运行mirai_ok后无法加载流泪猫

### ISSUE THREAD

**Issue by Pika-Lee** [LXY1226/MiraiOK#41]
**描述这个Bug**
更新1.9.1版本后，如不使用管理员载入console，加载native时会报错，且无法载入流泪猫（1.9.0无该问题）

**复现步骤**
分别使用管理员/非管理员模式运行miraiOK_windows-386.exe，管理员模式可正常运行，非管理员模式会报错。

**期望的行为**
miraiOK无需管理员模式便可正常运行

**截图和日志**
![管理员](https://user-images.githubusercontent.com/23114990/92625791-b2480980-f2fb-11ea-90e3-f91e2d928fff.png)
![非管理员](https://user-images.githubusercontent.com/23114990/92625811-b5db9080-f2fb-11ea-8739-8befcde2b664.png)

**运行环境**
 - 操作系统：[例子：Windows 10 1909]
 - `mirai core` 版本：[例子：1.2.2]
 - `mirai console` 版本：[例子：1.0-M4-DEV-3]
 - `mirai native` 版本：[例子：1.9.1]
 - `Java` 运行时版本：[例子：1.8.0 252]

**更多信息**
定位了一下，是mirai_ok的问题，如果直接用bat载入console，不会复现该问题。

**Comment by Pika-Lee** [comment]
另外请问下autologin大概什么时候能支持新版的mirai呢？我把旧版的config.txt放进去貌似没有用。

**Comment by LXY1226** [comment]
全删掉重新下载，权限问题，或者报给native让他们处理
自动登录等console发m5
