### ISSUE TITLE
miraiOK_windows_386 账号验证问题

### ISSUE THREAD

**Issue by AdorableParker** [LXY1226/MiraiOK#47]
之前版本的不是有个链接给出，然后可以进行扫码验证吗，最新版本的并没有这个链接给出，手机端也并不弹出任何关于验证的消息，无法进行验证操作，这个怎么解决

版本是 MiraiOK 20200915.071520 windows-386

**Comment by nazhendenb** [comment]
+1  我也遇到一样的问题，  我还以为点蓝色的字可以跳转链接..

**Comment by singoonhe** [comment]
点蓝色的字不能跳转链接的原因，可能是因为你们没用管理员权限打开

**Comment by ssshinchan** [comment]
我也遇到了,以管理员打开后点蓝色的字就会打开qq的登录页面了,然后扫码后关掉那个弹出框就登录成功了
