### ISSUE TITLE
supervisord怎么启动，执行的时候提示no such file

### ISSUE THREAD

**Issue by llllllllu** [LXY1226/MiraiOK#5]
之前用的wrapper，昨天开始一直提示检测Console-Pure损坏，一直下载，下载完成启动的时候又提示失败，又下载。。。
现在想使用MiraiOK,执行命令可以正常启动。但是在supervisord配置里面不知道怎么写。下面是我的supervisord配置文件。miraiOK_linux_amd64在root目录下
[program:qqbot]
command=./miraiOK_linux_amd64
directory=/root/
user=root
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/home/qqboot/log/qqbot.log
希望得到回复，非常感谢

**Comment by Tim-Paik** [comment]
（我不是官方人员，并且没怎么用过supervisord
这个配置文件无法启动吗？
有什么报错吗？

**Comment by llllllllu** [comment]
报错就是 no such file。我也不太明白这个原理，不过用screen  可以后台运行了，关闭吧，非常感谢

**Comment by Tim-Paik** [comment]
以我的常识，这里的command应该是个绝对路径吧（即`/root/miraiOK_linux_amd64`）
