### ISSUE TITLE
登录提示QQ版本过低，需要更新

### ISSUE THREAD

**Issue by EdrowsLuo** [LXY1226/MiraiOK#59]
19:00:03 [INFO] [BOT *********] Logging in...
 19:00:13 [INFO] [NETWORK] Connected to server msfwifi.3g.qq.com:8080
 19:00:13 [INFO] [NETWORK] Send: wtlogin.login
 19:00:13 [INFO] [NETWORK] Recv: Error(title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo= )
 19:00:13 [INFO] [Command] ********* login failed -> Error(title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo= )

**Comment by yzqd9527** [comment]
如果密码没错账号没封的话请尝试使用mirai2.0.0过滑块验证登陆

**Comment by EdrowsLuo** [comment]
> 如果密码没错账号没封的话请尝试使用mirai2.0.0过滑块验证登陆

谢谢，但是我已经用新版mirai/mirai-console自己封了个包解决问题了 :)
