### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by llllllllu** [LXY1226/MiraiOK#6]
启动后下载的mirai-console包损坏，一直重复下载
./miraiOK_linux_amd64 
[09:55:51.2947] I MiraiOK 20200629.160938 running at linux-amd64
[09:55:51.2948] I 此程序以Affero GPL3.0协议发布，使用时请遵守协议
[09:55:51.2948] I 代码库: github.com/LXY1226/MiraiOK gitee.com/LXY1226/MiraiOK
[09:55:51.3533] I JRE: java version "1.8.0_121"
[09:55:51.3533] I JRE: Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
[09:55:51.3533] I JRE: Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
[09:55:51.3534] I 删除.lastupdate来在下次强制检查更新
[09:55:51.3534] I 启动Mirai...
Using proxy: null
You are running Mirai-Console-Wrapper under /root
All additional libraries are located at /root/libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version .. 
Stay on current version.
Fetching Newest Console Version of Pure
Stay on current version.
Version check complete, starting Mirai
shadow-Protocol:/root/content/mirai-core-qqandroid-1.0.3.jar
Console        :/root/content/mirai-console-1.0-dev-1.jar
Root           :/root/
Found mirai-console file broken, re-downloading...
You are running Mirai-Console-Wrapper under /root
All additional libraries are located at /root/libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version .. 
Stay on current version.
Fetching Newest Console Version of Pure
Local Console-Pure Version: 0.0.0 | Newest KEEP Console-Pure Version: 1.0-dev-1
Updating Console-Pure from V0.0.0 -> V1.0-dev-1
GitHub mamoe.github.io: https://mamoe.github.io/mirai-repo/shadow/mirai-console/mirai-console-1.0-dev-1.jar
GitHub mirai-repo: https://raw.githubusercontent.com/mamoe/mirai-repo/master/shadow/mirai-console/mirai-console-1.0-dev-1.jar

GitHub mamoe.github.io
Progress:                                           | 0MB
无法从 GitHub mamoe.github.io 下载. 正在更换下一个源

GitHub mirai-repo
Progress: ########################################  | Complete
Version check complete, starting Mirai
shadow-Protocol:/root/content/mirai-core-qqandroid-1.0.3.jar
Console        :/root/content/mirai-console-1.0-dev-1.jar
Root           :/root/
**Found mirai-console file broken, re-downloading...**
You are running Mirai-Console-Wrapper under /root
All additional libraries are located at /root/libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version .. 
Stay on current version.
Fetching Newest Console Version of Pure
Local Console-Pure Version: 0.0.0 | Newest KEEP Console-Pure Version: 1.0-dev-1
Updating Console-Pure from V0.0.0 -> V1.0-dev-1
GitHub mamoe.github.io: https://mamoe.github.io/mirai-repo/shadow/mirai-console/mirai-console-1.0-dev-1.jar
GitHub mirai-repo: https://raw.githubusercontent.com/mamoe/mirai-repo/master/shadow/mirai-console/mirai-console-1.0-dev-1.jar

GitHub mamoe.github.io
Progress:                                           | 0MB
无法从 GitHub mamoe.github.io 下载. 正在更换下一个源

GitHub mirai-repo
Progress: ########################################  | Complete
Version check complete, starting Mirai
shadow-Protocol:/root/content/mirai-core-qqandroid-1.0.3.jar
Console        :/root/content/mirai-console-1.0-dev-1.jar
Root           :/root/
**Found mirai-console file broken, re-downloading...**
You are running Mirai-Console-Wrapper under /root
All additional libraries are located at /root/libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version .. 
Stay on current version.
Fetching Newest Console Version of Pure
Local Console-Pure Version: 0.0.0 | Newest KEEP Console-Pure Version: 1.0-dev-1
Updating Console-Pure from V0.0.0 -> V1.0-dev-1
GitHub mamoe.github.io: https://mamoe.github.io/mirai-repo/shadow/mirai-console/mirai-console-1.0-dev-1.jar
GitHub mirai-repo: https://raw.githubusercontent.com/mamoe/mirai-repo/master/shadow/mirai-console/mirai-console-1.0-dev-1.jar

GitHub mamoe.github.io
Progress:                                           | 0MB
无法从 GitHub mamoe.github.io 下载. 正在更换下一个源

GitHub mirai-repo
Progress: ########################################  | Complete
Version check complete, starting Mirai
shadow-Protocol:/root/content/mirai-core-qqandroid-1.0.3.jar
Console        :/root/content/mirai-console-1.0-dev-1.jar
Root           :/root/
Found mirai-console file broken, re-downloading...
You are running Mirai-Console-Wrapper under /root
All additional libraries are located at /root/libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version .. 
Stay on current version.
Fetching Newest Console Version of Pure
Local Console-Pure Version: 0.0.0 | Newest KEEP Console-Pure Version: 1.0-dev-1
Updating Console-Pure from V0.0.0 -> V1.0-dev-1
GitHub mamoe.github.io: https://mamoe.github.io/mirai-repo/shadow/mirai-console/mirai-console-1.0-dev-1.jar
GitHub mirai-repo: https://raw.githubusercontent.com/mamoe/mirai-repo/master/shadow/mirai-console/mirai-console-1.0-dev-1.jar

GitHub mamoe.github.io
Progress:                                           | 0MB
无法从 GitHub mamoe.github.io 下载. 正在更换下一个源

**Comment by Tim-Paik** [comment]
这很明显你的网络问题啊，可以尝试挂tz、、
天朝就这样XD

**Comment by llllllllu** [comment]
> 这很明显你的网络问题啊，可以尝试挂tz、、
> 天朝就这样XD

有加粗的字，是下载好了，提示文件损坏，一直重复下载

**Comment by Tim-Paik** [comment]
是不是无限循环更新的问题？
（即更新后更新的文件为上一个版本，但上一个版本提示更新，于是重新下载然后无限循环、、）
如果是的话那我们应该没什么办法，只能等repo修复（大概）
或者你可以试试第一个源？
PS：我这边是没有问题的

**Comment by Tim-Paik** [comment]
好的，我出问题了
 
来自[https://github.com/mamoe/mirai](https://github.com/mamoe/mirai)的readme
> 注意：mirai-console 后端和 pure 前端正在进行完全的重构，master 分支将不再维护。
mirai-console 将在短时间内不可用。

**Comment by Tim-Paik** [comment]
备份所有文件并清空miraiOK目录下所有文件后，重启miraiOK，问题解决，不要直接java -jar启动就OK了
我是这么解决的，你可以试试？

**Comment by llllllllu** [comment]
> 
> 
> 备份所有文件并清空miraiOK目录下所有文件后，重启miraiOK，问题解决，不要直接java -jar启动就OK了
> 我是这么解决的，你可以试试？

可以了，谢谢啦

**Comment by LXY1226** [comment]
清空重启万金油
